# fly.toml app configuration file generated for testaurant-api on 2025-09-09T19:34:53-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'testaurant-api'
primary_region = 'atl'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 25

  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    timeout = "2s"
    path = "/admin/login/"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
