# Generated by Django 4.1 on 2025-03-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_first_name_user_hire_date_user_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_tests',
            field=models.ManyToManyField(blank=True, related_name='assigned_users', to='api.test_this'),
        ),
    ]
