# Generated by Django 4.1 on 2025-04-02 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_assigned_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='con_dairy',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
