# Generated by Django 4.1 on 2025-05-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_food_con_dairy'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='con_dairy',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
