# Generated by Django 4.1 on 2025-05-26 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_drink_con_dairy'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='is_vegan',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drink',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='is_vegan',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='is_vegetarian',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
