# Generated by Django 4.1 on 2025-08-19 23:01

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_drink_created_at_drink_updated_at_food_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=60)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurants_owned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EditLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('Test', 'Test'), ('Question', 'Question'), ('Drink', 'Drink'), ('Food', 'Food')], max_length=20)),
                ('item_id', models.PositiveIntegerField()),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='update', max_length=10)),
                ('item_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('editor_name_snapshot', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('edit_date', models.DateTimeField(auto_now_add=True)),
                ('editor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_logs', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edit_logs', to='api.restaurant')),
            ],
            options={
                'ordering': ['-edit_date'],
            },
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['name'], name='api_restaur_name_105a37_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurant',
            index=models.Index(fields=['city', 'state'], name='api_restaur_city_a2b79c_idx'),
        ),
        migrations.AddIndex(
            model_name='editlog',
            index=models.Index(fields=['item_type', 'item_id'], name='api_editlog_item_ty_1876ff_idx'),
        ),
        migrations.AddIndex(
            model_name='editlog',
            index=models.Index(fields=['edit_date'], name='api_editlog_edit_da_604c25_idx'),
        ),
    ]
