# Generated by Django 4.1 on 2023-02-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_this',
            name='question_new',
            field=models.ManyToManyField(blank=True, related_name='question_new', to='api.question_new'),
        ),
    ]
