# Generated by Django 4.1 on 2025-08-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_food_restaurant_question_new_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editlog',
            name='item_type',
            field=models.CharField(choices=[('Test', 'Test'), ('Question', 'Question'), ('Drink', 'Drink'), ('Food', 'Food'), ('User', 'User')], max_length=20),
        ),
    ]
